spring:
  application:
    name: reservation-service
  cloud:
    consul:
      host: localhost
      port: 8500
  output.ansi.enabled: ALWAYS


---
spring:
  profiles: zone1
  cloud:
    consul:
      discovery:
        instanceZone: zone1
